import { RequestType } from '../enum/request-type.enum';

export const REQUEST_IMPORT_COLUMNS: Record<RequestType, string[]> = {
  [RequestType.PRODUCT_CREATE]: [
    'product_code',
    'product_name',
    'description',
    'category_code',
    'brand_code',
    'supplier_code',
    'has_variants',
    'unit',
    'product_sku',
    'product_barcode',
    'base_price',
    'selling_price',
    'minimum_stock',
    'maximum_stock',
    'variant_code',
    'variant_name',
    'variant_sku',
    'variant_barcode',
    'variant_attributes',
    'variant_base_price',
    'variant_selling_price',
    'warehouse_code',
    'quantity',
  ],

  [RequestType.PRODUCT_UPDATE]: [
    'product_code',
    'product_name',
    'description',
    'category_code',
    'brand_code',
    'supplier_code',
    'unit',
    'product_sku',
    'product_barcode',
    'base_price',
    'selling_price',
    'minimum_stock',
    'maximum_stock',
  ],

  [RequestType.VARIANT_CREATE]: [
    'product_code',
    'variant_code',
    'variant_name',
    'variant_sku',
    'variant_barcode',
    'variant_attributes',
    'base_price',
    'selling_price',
    'warehouse_code',
    'quantity',
  ],

  [RequestType.VARIANT_UPDATE]: [
    'product_code',
    'variant_code',
    'variant_name',
    'variant_sku',
    'variant_barcode',
    'variant_attributes',
    'base_price',
    'selling_price',
  ],

  [RequestType.STOCK_IN]: [
    'product_code',
    'variant_code',
    'warehouse_code',
    'quantity',
    'base_price',
    'selling_price',
  ],

  [RequestType.STOCK_OUT]: [
    'product_code',
    'variant_code',
    'warehouse_code',
    'quantity',
    'base_price',
    'selling_price',
  ],

  [RequestType.STOCK_TRANSFER]: [
    'product_code',
    'variant_code',
    'from_warehouse_code',
    'to_warehouse_code',
    'quantity',
    'base_price',
    'selling_price',
  ],

  [RequestType.STOCK_ADJUSTMENT]: [
    'product_code',
    'variant_code',
    'warehouse_code',
    'adjustment_type',
    'quantity',
    'reason',
    'base_price',
    'selling_price',
  ],
};
